name: Build

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/c4deszes/arm-gcc-docker:v1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset armgcc-debug-unix
      
      - name: Build
        run: cmake --build --preset build-test-armgcc-debug-unix
